name: xene_dart

packages:
  - packages/*

scripts:
  analyze:
    run: melos exec -- "dart analyze"
    description: Run dart analyze on all packages
  format:
    run: melos exec -- "dart format ."
    description: Run dart format on all packages
  test:
    run: melos exec -- "dart test"
    description: Run tests on all packages
