name: xene_dart
description: Xene Dart Monorepo Workspace
version: 1.0.0
publish_to: none

environment:
  sdk: "^3.11.5"

dependencies:
  melos: ^7.0.0
  device_preview_plus: ^2.7.1

workspace:
  - packages/xene_app
  - packages/xene_backend
  - packages/xene_domain

melos:
  packages:
    - packages\xene_app
    - packages\xene_backend
    - packages\xene_domain
  command:
    bootstrap:
      usePubspecOverrides: true
      runPubGetInParallel: false
