// @ts-check
// Static config for the visualizer page. The page ships as a bundled WebView
// asset with no session and no env access, so the Supabase project URL is
// baked in here. Everything reachable through it is public-read by design
// (the `av-tracks` bucket is a public bucket; no keys, no tokens).
/** @type {any} */ (window).XENE_AV_CONFIG = {
  // Regenerated by Dashboard > AV Tracks on every playlist change.
  playlistManifestUrl:
    'https://zwhabeyrhiqwzzttwfrk.supabase.co/storage/v1/object/public/av-tracks/playlist.json',
};
