// @ts-check
// Playlist panel — floating, draggable list of saved AV tracks.
//
// Users see one title per track (never the stems). Tapping a track fetches its
// bundle from Supabase public storage, loads it into the StemEngine, applies
// the saved reactivity/look settings, and plays. If the track has a
// precomputed chart, only master + vocals are downloaded (chart drives the
// rest); otherwise all stems come down and live DSP does the work — the chart
// is an optimisation, never a requirement.
//
// app.js owns the engine + settings; it hands us hooks via init():
//   { engine, applySettings(settings), onTrackLoaded(track, loadedSlots) }

(function () {
  'use strict';

  const LS_POS = 'dancingPoints.playlistPanel';
  /** @type {any} */
  const cfg = /** @type {any} */ (window).XENE_AV_CONFIG || {};

  /** @type {any} */ let engine = null;
  /** @type {any} */ let applySettings = null;
  /** @type {any} */ let onTrackLoaded = null;

  /** @type {any[]} */ let tracks = [];
  /** @type {string|null} */ let activeId = null;
  /** @type {string|null} */ let loadingId = null;
  let loadSeq = 0;

  /** @type {any} */ let panel, listEl, statusEl;

  /** @param {{engine:any, applySettings:Function, onTrackLoaded:Function}} hooks */
  function init(hooks) {
    engine = hooks.engine;
    applySettings = hooks.applySettings;
    onTrackLoaded = hooks.onTrackLoaded;
    buildPanel();
    refresh();
  }

  async function refresh() {
    const url = cfg.playlistManifestUrl;
    if (!url) { setStatus('no playlist configured'); return; }
    setStatus('loading…');
    try {
      // cache-buster: the manifest is regenerated by the dashboard and served
      // with a short CDN TTL — force freshness on open/refresh.
      const res = await fetch(url + '?t=' + Date.now(), { cache: 'no-store' });
      if (!res.ok) throw new Error('HTTP ' + res.status);
      const manifest = await res.json();
      tracks = Array.isArray(manifest.tracks) ? manifest.tracks : [];
      console.log('[playlist] manifest loaded:', tracks.length, 'tracks');
      setStatus(tracks.length === 0 ? 'playlist is empty' : '');
      render();
    } catch (err) {
      console.warn('[playlist] manifest fetch failed', err);
      setStatus('playlist unavailable');
    }
  }

  /** @param {any} track */
  async function loadTrack(track) {
    if (loadingId === track.id) return;
    if (engine && engine.unlockAudio) {
      engine.unlockAudio().catch((err) => console.warn('[playlist] audio unlock failed', err));
    }
    const seq = ++loadSeq;
    loadingId = track.id;
    render();
    try {
      // chart mode: only the audible master + the vocal stem (raw waveform for
      // the brain trail) need to travel; the chart drives everything else.
      //
      // DEV A/B knob: localStorage.setItem('dancingPoints.abMode','1') + reload
      // → downloads ALL stems AND the chart, installs NO chart (pure live DSP),
      // and stashes the chart at window.__avChart. Flip live in the console:
      //   xeneEngine.setChart(window.__avChart)  // chart drive
      //   xeneEngine.setChart(null)              // live DSP
      const abMode = localStorage.getItem('dancingPoints.abMode') === '1';
      let chart = null;
      let fileEntries = Object.entries(track.files || {});
      if (track.chartUrl) {
        try {
          const res = await fetch(track.chartUrl);
          if (!res.ok) throw new Error('HTTP ' + res.status);
          chart = await res.json();
          if (!abMode) {
            fileEntries = fileEntries.filter(([slot]) => slot === 'original' || slot === 'vocals');
          }
        } catch (err) {
          console.warn('[playlist] chart fetch failed — falling back to full stems', err);
          chart = null;
          fileEntries = Object.entries(track.files || {});
        }
      }
      /** @type {any} */ (window).__avChart = chart;
      if (abMode) {
        console.log('[playlist] A/B mode: full stems + live DSP; chart stashed at window.__avChart');
      }
      if (engine.setAudibleUrl) engine.setAudibleUrl(track.files && track.files.original);

      console.log('[playlist] fetching', track.title, fileEntries.map(([s]) => s).join('+'));
      const parts = await Promise.all(fileEntries.map(async ([slot, url]) => {
        const res = await fetch(/** @type {string} */ (url));
        if (!res.ok) throw new Error(slot + ': HTTP ' + res.status);
        return /** @type {[string, ArrayBuffer]} */ ([slot, await res.arrayBuffer()]);
      }));
      if (seq !== loadSeq) return; // superseded by a newer tap

      engine.reset();
      for (const [slot, buf] of parts) await engine.setSlot(slot, buf);
      if (seq !== loadSeq) return;

      if (engine.setChart) engine.setChart(abMode ? null : chart);
      if (applySettings) applySettings(track.settings);
      engine.seek(0);
      engine.play();
      activeId = track.id;
      if (onTrackLoaded) onTrackLoaded(track, parts.map(([slot]) => slot));
      setStatus('');
    } catch (err) {
      console.error('[playlist] load failed', track.id, err);
      setStatus('load failed: ' + (err && /** @type {any} */ (err).message));
    } finally {
      if (seq === loadSeq) { loadingId = null; render(); }
    }
  }

  /** Auto-advance: called from engine.onEnded (app.js). No-op unless a
      playlist track was playing. */
  function advance() {
    if (!activeId || tracks.length === 0) return;
    const i = tracks.findIndex((t) => t.id === activeId);
    const next = tracks[(i + 1) % tracks.length];
    if (next) loadTrack(next);
  }

  // ---------- panel DOM ----------
  function buildPanel() {
    panel = document.createElement('div');
    panel.id = 'playlistPanel';
    panel.innerHTML =
      '<div class="pl-head" id="plHead">' +
      '  <span class="pl-title">Playlist</span>' +
      '  <span class="pl-actions">' +
      '    <button class="pl-btn" id="plRefresh" title="reload playlist">&#8635;</button>' +
      '    <button class="pl-btn" id="plMin" title="collapse">&ndash;</button>' +
      '  </span>' +
      '</div>' +
      '<div class="pl-status" id="plStatus"></div>' +
      '<div class="pl-list" id="plList"></div>';
    document.body.appendChild(panel);
    listEl = panel.querySelector('#plList');
    statusEl = panel.querySelector('#plStatus');
    panel.querySelector('#plRefresh').addEventListener('click', refresh);
    panel.querySelector('#plMin').addEventListener('click', () => {
      panel.classList.toggle('min');
    });
    makeDraggable(panel.querySelector('#plHead'));
    restorePosition();
  }

  /** @param {string} msg */
  function setStatus(msg) {
    if (statusEl) {
      statusEl.textContent = msg;
      statusEl.style.display = msg ? '' : 'none';
    }
  }

  function render() {
    if (!listEl) return;
    listEl.innerHTML = '';
    tracks.forEach((t, i) => {
      const el = document.createElement('button');
      el.type = 'button';
      el.className = 'pl-track'
        + (t.id === activeId ? ' active' : '')
        + (t.id === loadingId ? ' loading' : '');
      const sub = t.id === loadingId ? 'loading…' : (t.artist || '');
      el.innerHTML =
        '<span class="pl-n">' + (i + 1) + '</span>' +
        '<span class="pl-meta"><span class="pl-name"></span><span class="pl-sub"></span></span>';
      el.querySelector('.pl-name').textContent = t.title || 'Untitled';
      el.querySelector('.pl-sub').textContent = sub;
      el.addEventListener('click', () => loadTrack(t));
      listEl.appendChild(el);
    });
  }

  // ---------- drag (whole panel follows the header) ----------
  /** @param {HTMLElement} handle */
  function makeDraggable(handle) {
    let startX = 0, startY = 0, baseL = 0, baseT = 0, dragging = false;
    handle.addEventListener('pointerdown', (/** @type {any} */ e) => {
      if (e.target.closest('.pl-btn')) return; // buttons stay clickable
      dragging = true;
      startX = e.clientX; startY = e.clientY;
      const r = panel.getBoundingClientRect();
      baseL = r.left; baseT = r.top;
      handle.setPointerCapture(e.pointerId);
    });
    handle.addEventListener('pointermove', (/** @type {any} */ e) => {
      if (!dragging) return;
      const l = Math.max(4, Math.min(window.innerWidth - 80, baseL + e.clientX - startX));
      const t = Math.max(4, Math.min(window.innerHeight - 48, baseT + e.clientY - startY));
      panel.style.left = l + 'px';
      panel.style.top = t + 'px';
    });
    const end = (/** @type {any} */ e) => {
      if (!dragging) return;
      dragging = false;
      try { handle.releasePointerCapture(e.pointerId); } catch (_e) { /* released */ }
      try {
        localStorage.setItem(LS_POS, JSON.stringify({ left: panel.style.left, top: panel.style.top }));
      } catch (_e) { /* storage unavailable */ }
    };
    handle.addEventListener('pointerup', end);
    handle.addEventListener('pointercancel', end);
  }

  function restorePosition() {
    try {
      const p = JSON.parse(localStorage.getItem(LS_POS) || 'null');
      if (p && p.left && p.top) { panel.style.left = p.left; panel.style.top = p.top; }
    } catch (_e) { /* corrupt state → default position */ }
  }

  /** @type {any} */ (window).XenePlaylist = { init, refresh, advance };
})();
