name: Semgrep

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@v4
      - run: |
          semgrep ci \
            --config=p/dart \
            --config=p/security-audit \
            --config=p/secrets \
            --config=p/sql \
            --config=p/postgresql \
            --config=p/owasp-top-10
